# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 03:23
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [("speaker", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="confirmation_key",
            field=hashid_field.field.HashidField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                blank=True,
                min_length=7,
                null=True,
            ),
        )
    ]
