# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_create_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='behance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='google',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='site',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
