# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_speaker_confirmation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
