# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0004_auto_20170305_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='behance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
