# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0005_auto_20170305_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
